[pytest]

# Параметры запуска
addopts =
    --alluredir=./allure-results
    -v

# Корректное отображения кириллицы
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

# Где искать тесты
testpaths = tests

# Паттерны поиска
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Маркеры

markers =
    api: тесты API
    ui: тесты UI
    forward: тесты прямого геокодирования
    reverse: тесты обратного геокодирования
    positive: позитивные тесты
    negative: негативные тесты