[pytest]

disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

# Где искать тесты
testpaths = tests

# Паттерны поиска
python_files = test_*.py
python_classes = Test*
python_functions = test_*